CLASS zbp_i_230_dmo_booking_m DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zi_230_dmo_travel_m.
protected section.
private section.
ENDCLASS.



CLASS ZBP_I_230_DMO_BOOKING_M IMPLEMENTATION.
ENDCLASS.
